name: orby
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.3.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  cupertino_icons: ^1.0.8
  geocoding: ^4.0.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_analytics: ^11.4.6
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/orby_logo.png
    - assets/images/profile_pic.png
    - assets/images/forum.png
    - assets/images/patrocinio.png
    - assets/images/sangue.png
    - assets/images/info.png
    - assets/images/news.png
    - assets/images/antoniorocha.jpg
    - assets/images/augustooliveira.jpg
    - assets/images/elenavidal.jpeg
    - assets/images/elisareis.jpg
    - assets/images/isabeladuarte.jpg
    - assets/images/lucasferreira.jpg
    - assets/images/robertasilva.jpg
    - assets/images/sergiocosta.jpg
    - assets/images/sandraquintarelli.jpg
    - assets/images/sad.png
