// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK3uWYwFVo7EaCct4F8MxYIZvnoUT2MOA',
    appId: '1:900124114882:web:5cba375a073f9c7f4ee05b',
    messagingSenderId: '900124114882',
    projectId: 'flutterorby',
    authDomain: 'flutterorby.firebaseapp.com',
    storageBucket: 'flutterorby.firebasestorage.app',
    measurementId: 'G-1LJL12C872',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFazSjBG6SEvZB87Jv0wCELgByMS8FzHQ',
    appId: '1:900124114882:android:14017eb03e74051b4ee05b',
    messagingSenderId: '900124114882',
    projectId: 'flutterorby',
    storageBucket: 'flutterorby.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzI5O5HjRkiQFbb28hO8OaamYHnGpkTaw',
    appId: '1:900124114882:ios:f159313d0329eb044ee05b',
    messagingSenderId: '900124114882',
    projectId: 'flutterorby',
    storageBucket: 'flutterorby.firebasestorage.app',
    iosBundleId: 'com.example.orby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzI5O5HjRkiQFbb28hO8OaamYHnGpkTaw',
    appId: '1:900124114882:ios:f159313d0329eb044ee05b',
    messagingSenderId: '900124114882',
    projectId: 'flutterorby',
    storageBucket: 'flutterorby.firebasestorage.app',
    iosBundleId: 'com.example.orby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK3uWYwFVo7EaCct4F8MxYIZvnoUT2MOA',
    appId: '1:900124114882:web:54d52471cfb322fb4ee05b',
    messagingSenderId: '900124114882',
    projectId: 'flutterorby',
    authDomain: 'flutterorby.firebaseapp.com',
    storageBucket: 'flutterorby.firebasestorage.app',
    measurementId: 'G-3ER7CB6NZF',
  );
}
